# MS: CHANGED SYSPORT		=	-DLINUX -DGENERIC_SYSV
# This is how my Linux works.

SYSPORT		=	-DLINUX -DPOSIX

CPP             =       g++ -I..
CC		=	g++ -I..
LD		=	g++
MKDPND		=	g++ -MM $(CFL)
LEX		=	flex
YACC		=	bison -y
DIFF		=	diff

ZONEDIR		=	zon/
