#pragma once

#include "essential.h"
#include "values.h"

#include <memory>

class CAccountConfig;
class CByteBuffer;
class CServerConfiguration;
class apply_function_type;
class blk_file_type;
class cCaptainHook;
class cCombatList;
class cMultiMaster;
class cMultiMaster;
class cNamelist;
class command_info;
class damage_chart_type;
class descriptor_data;
class dil_func_type;
class dilprg;
class diltemplate;
class file_index_type;
class log_buffer;
class money_type;
class race_info_type;
class shi_info_type;
class skill_interval;
class spell_info_type;
class tick_function_type;
class tree_type;
class trie_type;
class unit_data;
class unit_function_array_type;
class unit_vector_data;
class wpn_info_type;
class zone_info_type;
class zone_type;
//========================================================================================================================
// extern requirement_type                 pc_race_base[];
// extern requirement_type                 spl_requirement[];
extern CAccountConfig                   g_cAccountConfig;
extern CByteBuffer                      g_FileBuffer;
extern CServerConfiguration             g_cServerConfig;
extern apply_function_type              apf[];
extern blk_file_type                   *inven_bf;
extern cCaptainHook                     CaptainHook;
extern cCombatList                      CombatList;
extern cMultiMaster                     Multi;
extern cNamelist                        persist_namelist;
extern char                             etext;
extern char                             libdir[];
extern char                             plydir[];
extern char                             world_boottime[];
extern char                             zondir[];
extern char                            *credits;
extern char                            *goodbye;
extern char                            *info;
extern char                            *logo;
extern char                            *motd;
extern char                            *news;
extern char                            *wizlist;
extern char                           **player_name_list;
extern command_info                     cmd_a_social;
extern command_info                     cmd_auto_combat;
extern command_info                     cmd_auto_damage;
extern command_info                     cmd_auto_death;
extern command_info                     cmd_auto_enter;
extern command_info                     cmd_auto_extract;
extern command_info                     cmd_auto_msg;
extern command_info                     cmd_auto_save;
extern command_info                     cmd_auto_tick;
extern command_info                     cmd_auto_unknown;
extern command_info                     cmd_info[];
extern command_info                    *cmd_follow;
extern const char                      *abil_text[];
extern const char                      *arm_text[];
extern const char                      *bodyparts[];
extern const char                      *char_flags[];
extern const char                      *char_pos[];
extern const char                      *char_sex[];
extern const char                      *color_liquid[];
extern const char                      *compile_time;
extern const char                      *compile_date;
extern const char                      *connected_types[];
extern const char                      *dirs[];
extern const char                      *drinks[];
extern const char                      *enter_dirs[];
extern const char                      *equip_pos[];
extern const char                      *fillwords[];
extern const char                      *fullness[];
extern const char                      *month_name[];
extern const char                      *npc_class_types[];
extern const char                      *npc_flags[];
extern const char                      *obj_flags[];
extern const char                      *obj_pos[];
extern const char                      *obj_types[];
extern const char                      *pc_flags[];
extern const char                      *pc_race_adverbs[];
extern const char                      *pc_races[];
extern const char                      *room_flags[];
extern const char                      *room_landscape[];
extern const char                      *sfb_flags[];
extern const char                      *shi_text[];
extern const char                      *ski_text[];
extern const char                      *spl_text[];
extern const char                      *unit_flags[];
extern const char                      *unit_manipulate[];
extern const char                      *unit_open_flags[];
extern const char                      *unit_status[];
extern const char                      *weekdays[];
extern const char                      *where[];
extern const char                      *wpn_text[];
extern const int                        drink_aff[LIQ_MAX + 2][3];
extern const int                        movement_loss[];
extern const int                        rev_dir[];
extern const sbit8                      time_light[];
extern const skill_interval             spell_skills[];
extern const skill_interval             how_good[];
extern const skill_interval             skill_skills[];
extern const skill_interval             weapon_skills[];
extern const time_t                     beginning_of_time;
extern const ubit8                      bodyparts_cover[31][5];
extern damage_chart_type                spell_chart[];
extern descriptor_data                 *descriptor_list;
extern descriptor_data                 *next_to_process;
extern dil_func_type                    dilfe_func[];
extern dilprg                          *dil_list;
extern dilprg                          *dil_list_nextdude;
extern diltemplate                     *nanny_dil_tmpl;
extern diltemplate                     *playerinit_tmpl;
extern int                              bModeBBS;
extern int                              bPipeSignal;
extern int                              events;
extern int                              g_nCorrupt;
extern int                              hit_location_table[];
extern int                              max_no_connections;
extern int                              max_no_players;
extern int                              memory_dijkstra_alloc;
extern int                              memory_npc_alloc;
extern int                              memory_obj_alloc;
extern int                              memory_pc_alloc;
extern int                              memory_room_alloc;
extern int                              memory_roomread_alloc;
extern int                              memory_zoneidx_alloc;
extern int                              memory_zonereset_alloc;
extern int                              mud_bootzone;
extern int                              mud_reboot;
extern int                              mud_shutdown;
extern int                              no_connections;
extern int                              no_players;
extern int                              player_convert;
extern int                              room_number;
extern int                              slow_death;
extern int                              sunlight;
extern int                              tics;
extern int                              wizlock;
extern int                              world_nochars;
extern int                              world_nonpc;
extern int                              world_noobjects;
extern int                              world_nopc;
extern int                              world_norooms;
extern int                              world_nozones;
extern log_buffer                       log_buf[];
extern money_type                       money_types[];
extern race_info_type                   race_info[];
extern sbit32                           player_id;
extern sbit8                            racial_ability[ABIL_TREE_MAX][PC_RACE_MAX];
extern sbit8                            racial_skills[SKI_TREE_MAX][PC_RACE_MAX];
extern sbit8                            racial_spells[SPL_TREE_MAX][PC_RACE_MAX];
extern sbit8                            racial_weapons[WPN_TREE_MAX][PC_RACE_MAX];
extern shi_info_type                    shi_info[];
extern spell_info_type                  spell_info[];
extern std::shared_ptr<file_index_type> corpse_fi;
extern std::shared_ptr<file_index_type> deathobj_fi;
extern std::shared_ptr<file_index_type> demigod_fi;
extern std::shared_ptr<file_index_type> head_fi;
extern std::shared_ptr<file_index_type> letter_fi;
extern std::shared_ptr<file_index_type> slime_fi;
extern std::shared_ptr<file_index_type> zombie_fi;
extern std::shared_ptr<zone_type>       boot_zone;
extern tick_function_type               tif[];
extern tree_type                        abil_tree[];
extern tree_type                        ski_tree[];
extern tree_type                        spl_tree[];
extern tree_type                        wpn_tree[];
extern trie_type                       *intr_trie;
extern ubit32                           memory_total_alloc;
extern ubit8                            g_nShout;
extern std::shared_ptr<unit_data>       combat_list;
extern std::shared_ptr<unit_data>       destroy_room;
extern std::shared_ptr<unit_data>       entry_room;
extern std::shared_ptr<unit_data>       seq_room;
extern std::shared_ptr<unit_data>       unit_list;
extern std::shared_ptr<unit_data>       void_room;
extern unit_function_array_type         unit_function_array[];
extern unit_vector_data                 unit_vector;
extern wpn_info_type                    wpn_info[];
extern zone_info_type                   zone_info;
