#include "tick_function_type.h"

#include "tif_affect.h"

tick_function_type tif[] = {{"Decay Corpse", tif_decay_corpse},
                            {"Destroy Corpse", tif_destroy_corpse},
                            {"Valhalla Return", tif_valhalla_ret},
                            {"Hitpoints On", tif_hit_on},
                            {"Hitpoints Off", tif_hit_off},
                            {"Magic Mod On", tif_mag_on},
                            {"Magic Mod Off", tif_mag_off},
                            {"Divine Mod On", tif_div_on},
                            {"Divine Mod Off", tif_div_off},
                            {"Strength Mod On", tif_str_on},
                            {"Strength Mod Off", tif_str_off},
                            {"Dexterity Mod On", tif_dex_on},
                            {"Dexterity Mod Off", tif_dex_off},
                            {"Constitution Mod On", tif_con_on},
                            {"Constitution Mod On", tif_con_off},
                            {"Charisma Mod On", tif_cha_on},
                            {"Charisma Mod Off", tif_cha_off},
                            {"Brain Mod On", tif_bra_on},
                            {"Brain Mod Off", tif_bra_off},
                            {"XXX", tif_armour_on},
                            {"XXX", tif_armour_on},
                            {"Spell-skill Mod On", tif_protect_on},
                            {"Spell-skill Mod Off", tif_protect_off},
                            {"Poison On", tif_poison_on},
                            {"Poison Off", tif_poison_off},
                            {"Poison Suffer", tif_poison_suffer},
                            {"Light/Dark Add", tif_light_add},
                            {"Light/Dark Sub", tif_light_sub},
                            {"Torch burning countdown", tif_torch_tick},
                            {"Eyes tingles", tif_eyes_tingle},
                            {"Blind On", tif_blind_on},
                            {"Blind Off", tif_blind_off},
                            {"Fear Tick Check", tif_fear_check},
                            {"Invisibility On", tif_invisibility_on},
                            {"Invisibility Off", tif_invisibility_off},
                            {"Sneak on", tif_sneak_on},
                            {"Sneak off", tif_sneak_off},
                            {"Sneak tick", tif_sneak_tick},
                            {"Hide on", tif_hide_on},
                            {"Hide off", tif_hide_off},
                            {"Nide tick", tif_hide_tick},
                            {"Nohide tick", tif_nohide_tick},
                            {"sleep on", tif_sleep_on},
                            {"sleep check", tif_sleep_check},
                            {"sleep off", tif_sleep_off},
                            {"bless on", tif_bless_on},
                            {"bless tick", tif_bless_tick},
                            {"bless off", tif_bless_off},
                            {"curse on", tif_curse_on},
                            {"curse off", tif_curse_off},
                            {"sancruary on", tif_sanctuary_on},
                            {"sanctuary tick", tif_sanctuary_tick},
                            {"sanctuary off", tif_sanctuary_off},
                            {"insanity on", tif_insanity_on},
                            {"insanity tick", tif_insanity_tick},
                            {"insanity off", tif_insanity_off},
                            {"protect from evil on", tif_prot_evil_on},
                            {"protect from evil off", tif_prot_evil_off},
                            {"sustain on", tif_sustain_on},
                            {"sustain tick", tif_sustain_tick},
                            {"sustain off", tif_sustain_off},
                            {"jail waiting", tif_jail_wait},
                            {"jail release", tif_jail_release},
                            {"plague on", tif_plague_on},
                            {"plague tick", tif_plague_tick},
                            {"plague off", tif_plague_off},
                            {"reward on", tif_reward_on},
                            {"reward off", tif_reward_off},
                            {"spell on", tif_spl_on},
                            {"spell off", tif_spl_off},
                            {"skill on", tif_ski_on},
                            {"skill off", tif_ski_off},
                            {"weapon on", tif_wpn_on},
                            {"weapon off", tif_wpn_off},
                            {"confusion on", tif_confusion_on},
                            {"confusion off", tif_confusion_off},
                            {"confusion tick", tif_confusion_tick},
                            {"buried destruct", tif_buried_destruct},
                            {"protection from good on", tif_prot_good_on},
                            {"protection from good off", tif_prot_good_off},
                            {"natural armour on", tif_armour_on},
                            {"natural armour off", tif_armour_on},
                            {"speed better", tif_speed_on},
                            {"speed worse", tif_speed_off}};
